#Jekyll configuration
tagline: "Connecting Ideas &amp; Getting Creative"
#pygments: true
markdown: kramdown  
highlighter: rouge  
exclude: [command.sh]
permalink: pretty
gems:
  - jekyll-redirect-from
paginate: 3
